Default: &defaults
  database: YesodTutorial1.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: YesodTutorial1_test.sqlite3
  <<: *defaults

Staging:
  database: YesodTutorial1_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: YesodTutorial1_production.sqlite3
  poolsize: 100
  <<: *defaults
